# frozen_string_literal: true

source 'https://rubygems.org'

gem 'activesupport'
gem 'benchmark'
gem 'fileutils'
gem 'csv'
gem 'json'
gem 'namae'
gem 'nokogiri'
gem 'pp'
gem 'rest-client'
gem 'street_address'
gem 'tty-table'
gem 'sqlite3'
gem 'ostruct'
gem 'google_drive'
gem 'aws-sdk-dynamodb'
gem 'fuzzy_match'
